export const NATIONALITIES = [
  { name: 'Australiana', languages: ['Inglês', 'Australiano nativo'] },
  { name: 'Canadense', languages: ['Inglês', 'Francês', 'Primeiro Canadense'] },
  { name: 'Checoslováquia', languages: ['Checo', 'Eslovaco', 'Alemão', 'Húngaro', 'Iídiche'] },
  { name: 'Francesa', languages: ['Francês'] },
  { name: 'Indiana', languages: ['Inglês', 'Urdu', 'Hindu', 'Bengali'] },
  { name: 'Norueguesa', languages: ['Norueguês'] },
  { name: 'Polonesa', languages: ['Polonês'] },
  { name: 'Britânica', languages: ['Inglês', 'Irlandês'] },
  { name: 'Estadunidense', languages: ['Inglês', 'Línguas nativas Norte Americanas'] },
  { name: 'URSS', languages: ['Russa'] },
  { name: 'Belga', languages: ['Holandês', 'Francês', 'Alemão'] },
  { name: 'Camaronesa', languages: ['Inglês', 'Francês'] },
  { name: 'Ceilão', languages: ['Inglês', 'Sinhala', 'Tamil'] },
  { name: 'Ciprus', languages: ['Grego', 'Turco'] },
  { name: 'Dinamarquesa', languages: ['Dinamarquês'] },
  { name: 'Gambia', languages: ['Inglês', 'Línguas Tribais diversas'] },
  { name: 'Ghanesa', languages: ['Inglês', 'Uma das 80 línguas tribais'] },
  { name: 'Grega', languages: ['Grego'] },
  { name: 'Queniana', languages: ['Inglês', 'Suaíli'] },
  { name: 'Luxemburguesa', languages: ['Luxemburguês', 'Francês', 'Alemão'] },
  { name: 'Malta', languages: ['Maltês', 'Inglês'] },
  { name: 'Neozelandesa', languages: ['Inglês', 'Maori'] },
  { name: 'Nigeriana', languages: ['Inglês', 'Hausa', 'Igbo', 'Yoruba'] },
  { name: 'Rhodesia', languages: ['Inglês', 'Shona', 'Nbele'] },
  { name: 'Sul africana', languages: ['Inglês', 'Holandês', 'Africâner', 'Línguas Africanas Nativas'] },
  { name: 'Espanhola', languages: ['Espanhol', 'Catalão', 'Basco'] },
  { name: 'Caribenha', languages: ['Inglês', 'Francês', 'Espanhol', 'Holandês', 'Creole'] },
  { name: 'Holandesa', languages: ['Holandês', 'Inglês', 'Alemão', 'Francês'] },
  { name: 'Yugolavávia', languages: ['Serbo-croata'] },
]
